### PR TITLE
Added streetlighting.

### PR DESCRIPTION
**Pull request by afdy**

### CODE REVIEW

**Comment by afdy** [comment]
Absolutely support it, its an awesome idea ;).

**Comment by jt-nti** [comment]
I really like the idea of ultra-local decision making for this kind of thing. It also sounds like a great way of making the most of an investment which has already been made in the infrastructure.

@afdy Please could you read the [Contributor License Agreement](https://manifesto.openeastleigh.uk/cla.html) and leave a comment if you agree to it. Thanks!

**Comment by pavsmith** [comment]
This is a really tricky one. As you say modern streetlights don't cost a lot to run, and subsequently don't generate a lot of pollution aside from, perhaps, some light pollution. We have one in our front window which doesn't bother us and does provide a fantastic water show when raining at night. So perhaps turn them off, but... it's not just a "local" thing, it's also a "people who use your street" thing and has a safety aspect. I suspect a lot of women would prefer that streets were lit after dark. So, on balance, I think no, I'd prefer them left on for that reason alone.

Vote: ❎

**Comment by afdy** [comment]
So, on balance, I think no, I'd prefer them left on for that reason alone.
> 
> Vote: ❎

This underscores exactly the problem though.  You have decided to vote to leave them "on for everybody" due to your own personal preferences, and voted against this option to allow local control.  This perpetuates the never ending discussion of "should they be on or off".

If you were to allow local control, individuals could make the best decision for their area as a community as you don't know how other people feel.

Consider a piece of road with no housing that doesn't need lighting - that could be off by default.
Consider some star gazers that don't like lighting - they should have that option.
Consider a well populated area with high crime, they may like lighting - they should have that option.

If, like you have done - one person tries to make the decision for the whole area without considering other individual perspectives and opinions, 50% of people will be upset with whatever the outcome.  If you let the community around the lamp post decide, you end up with lighting tuned to be perfect for whoever lives there!

I still strongly believe its the ideal option.  Can you suggest an alternative approach other than "all on" or "all off", or could you perhaps reconsider?

By changing to vote positively for this change - you could still choose to keep your lamp on, but you would avoid forcing your decisions onto people who want their lamp off...

**Comment by jt-nti** [comment]
@pavsmith that's a really good point, although the starting point for this idea is that the streets aren't lit for the whole night in Hampshire.

Perhaps the process for deciding whether lights should be turned on could take account of everyone who uses a street, not just the residents? A FixMyStreet for lights? The other thing I've been wondering about is the idea of residents paying. I could easily imagine that affluent areas end up with all their street lights on, while other areas stay in the dark.

I still really like the idea of local neighbourhoods having the power to decide on which streets are lit after dark though. What do you think about updating the proposal a bit @afdy?

**Comment by pavsmith** [comment]
For me it simply comes back to personal safety. Plus it can't only be about the locals making the decision, especially where the street is used as a thoroughfare by people on foot. Indeed I flip exactly the opposite way on streetlights in areas with no housing, as they're the least safe areas after dark, and I think therefore it is an area that needs to be lit. A final thought for the moment is the condition of footpaths in many places which are bad enough trip hazards in the daytime, let alone if you were trying to walk on them in the dark!

**Comment by jt-nti** [comment]
Just discovered that there's an [interactive map of street lights](http://lightsoninhampshire.co.uk/Public/ReportFault.aspx) which shows which ones are currently on a "Part Night Lighting" schedule.

**Comment by pavsmith** [comment]
Interestingly I was once again enjoying last evening's rain falling through the streetlight outside our window and then, i think about 2230, it turned itself off!

**Comment by afdy** [comment]
Ok made amendments to address funding and security concerns by @pavsmith

**Comment by afdy** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jt-nti** [comment]
I like the idea of more local control and I think it's worth getting this policy in, on the basis that it is over and above the street lighting provided by the county, which already includes a mixture of lighting schedules.

Vote: ✅

**Pull request merged**
